### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/prw_padreg/model_final.pth'

### ISSUE THREAD

**Issue by szh91** [zhongyingji/APNet#4] opened 2020-10-31 07:34 UTC

**Comment by zhongyingji** [comment] 2020-11-02 13:20
Make sure you've followed the steps, especially the model copying process in train.sh

**Comment by szh91** [comment] 2020-11-04 01:37
I have followd the steps and tried more times, it still appeared the same error FileNotFoundError: [Errno 2] No such file or directory: 'models/prw_padreg/model_final.pth'

**Comment by zhongyingji** [comment] 2020-11-04 01:47
Could you provided more detailed log information?

**Comment by zhongyingji** [comment] 2020-11-04 01:48
Can you provide more detailed log information?

**Comment by szh91** [comment] 2020-11-04 01:58
I taked these steps:
1  install maskrcnn_benchmark ( success)
2  Install APNet
3  download the  PRW-v16.04.20 dataset, put it into the path:     APTNet/dataset/PRW-v16.04.20
4  cp keypoint_pred/*  ./datatset/PRW-v16.04.20/
5  ln -s   ./datatset/PRW-v16.04.20/ maskrcnn_benchmark/data/datasets/PRW-v16.04.20
6  ./train.sh

![image](https://user-images.githubusercontent.com/30435832/98060333-4fe73180-1e84-11eb-9ca1-cbfd65141353.png)

**Comment by zhongyingji** [comment] 2020-11-04 02:27
I think the problem is you do not apply:
```
rm -rf build/
python setup.py build develop
```

Make sure you can run OIM. (I suggest you open `train.sh`, run OIM first for debugging purpose).

BTW, 3 and 5 is of the duplicated purpose.

**Comment by szh91** [comment] 2020-11-04 03:01
I apply the two line code that you offered, but it still error, does OIM has to run and succeed before running APNet?

**Comment by zhongyingji** [comment] 2020-11-04 03:14
Yes, APNet is built upon OIM. 
```
rm -rf models/
rm -rf build/
python setup.py build develop
mkdir models/
python tools/train_net.py --config-file "configs/reid/prw_R_50_C4.yaml" SOLVER.IMS_PER_BATCH 2 TEST.IMS_PER_BATCH 8 OUTPUT_DIR "models/prw_oim"
```
implement the above script step by step.
And paste the log if error occurs.

**Comment by szh91** [comment] 2020-11-04 03:23
Traceback (most recent call last):
  File "/home/szh/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'maskrcnn_benchmark/datasets/PRW-v16.04.20/frame_train.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_net.py", line 221, in <module>
    main()
  File "tools/train_net.py", line 213, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/szh/workspace/Deep_learning_code/new_reid/APNet/maskrcnn_benchmark/data/build.py", line 160, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/szh/workspace/Deep_learning_code/new_reid/APNet/maskrcnn_benchmark/data/build.py", line 50, in build_dataset
    dataset = factory(**args)
  File "/home/szh/workspace/Deep_learning_code/new_reid/APNet/maskrcnn_benchmark/data/datasets/prw_dataset.py", line 21, in __init__
    frame = loadmat(path)
  File "/home/szh/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 222, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/home/szh/.conda/envs/maskrcnn_benchmark/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/szh/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/home/szh/.conda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'maskrcnn_benchmark/datasets/PRW-v16.04.20/frame_train.mat'

**Comment by zhongyingji** [comment] 2020-11-04 06:19
You've placed the PRW in the wrong place. 
The path you've built is: `APNet/dataset/PRW-v16.04.20`
it should be `APNet/datasets/PRW-v16.04.20`

it's OK whether you place the original PRW or create a symlink in APNet/datasets

**Comment by szh91** [comment] 2020-11-04 07:12
so I try agian:
1 build the datasets path:  APNet/datasets/PRW-v16.04.20
2 cp keypoint_pred/*  ./datasets/PRW-v16.04.20/
3 rm -rf build/
4 python setup.py build develop
5 sh train.sh

but still error

**Comment by szh91** [comment] 2020-11-04 07:14
I checkd the APNet/models,   prw/packreg  and prw part have last_checkpoin, but no such file in prw_oim

**Comment by zhongyingji** [comment] 2020-11-04 07:19
Could you just run the OIM with the script above for debugging? 
You'd better paste the error information so i can know where the error occurs

**Comment by szh91** [comment] 2020-11-04 07:41
I the create path   ./maskrcnn_benchmark/datasets/PRW-v16.04.20
copy the APNet/datasets/PRW-v16.04.20 to  ./maskrcnn_benchmark/datasets/PRW-v16.04.20
then run tran.sh  it can train

If I want test my dataset (images), and want to complte the image and extract the iamge feature (partial feature), so what should I do?
(Can you sent me your Wechat, so it will be much easier for me to learn from you)

**Comment by zhongyingji** [comment] 2020-11-04 07:54
Oops, sorry for the mistake. You are right, the correct path is:
`APNet/maskrcnn_benchmark/datasets/PRW-v16.04.20`
as the 1-3 line in `train.sh`

Once you trained the entire APNet, the model would be stored in `models/prw_padreg`. 
If you want to extract the part feature and store it or whatever, you can modify the code in
`APNet/maskrcnn_benchmark/data/datasets/eval_part_regressor.py `. 

Feel free to contact me with email.
I will close the issue. Open another issue if you have other problems.

**Closed as completed** 2020-11-04 07:54 UTC

**Comment by szh91** [comment] 2020-11-04 08:01
Thank you very much, ok I will contact you by email
